version: '3'

networks:
  elastic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

services:
  elasticsearch-node1:
    image: elasticsearch:5.2.1
    command: -Ediscovery.zen.ping.unicast.hosts=172.25.0.101,172.25.0.102,172.25.0.103 -Ebootstrap.memory_lock=true -Enetwork.host=0.0.0.0       -Enode.name=elasticsearch-node1 -Ediscovery.zen.minimum_master_nodes=2 
    volumes:
      - ./esdata-node1:/usr/share/elasticsearch/data
    restart: always
    expose:
      - 9200
      - 9300
    networks:
      elastic-network:
        ipv4_address: 172.25.0.101
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch-node2:
    image: elasticsearch:5.2.1
    command: -Ediscovery.zen.ping.unicast.hosts=172.25.0.101,172.25.0.102,172.25.0.103 -Ebootstrap.memory_lock=true -Enetwork.host=0.0.0.0       -Enode.name=elasticsearch-node2 -Ediscovery.zen.minimum_master_nodes=2 
    volumes:
      - ./esdata-node2:/usr/share/elasticsearch/data
    restart: always
    expose:
      - 9200
      - 9300
    networks:
      elastic-network:
        ipv4_address: 172.25.0.102
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch-node3:
    image: elasticsearch:5.2.1
    command: -Ediscovery.zen.ping.unicast.hosts=172.25.0.101,172.25.0.102,172.25.0.103 -Ebootstrap.memory_lock=true -Enetwork.host=0.0.0.0       -Enode.name=elasticsearch-node3 -Ediscovery.zen.minimum_master_nodes=2 
    volumes:
      - ./esdata-node3:/usr/share/elasticsearch/data
    restart: always
    expose:
      - 9200
      - 9300
    networks:
      elastic-network:
        ipv4_address: 172.25.0.103
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es-nginx:
    image: nginx:latest
    links:
      - elasticsearch-node1
      - elasticsearch-node2
      - elasticsearch-node3
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      elastic-network:
        ipv4_address: 172.25.0.104
    ports:
      - "9200:80"
  es-cerebro:
    image: yannart/cerebro:0.5.1
    volumes:
      - ./cerebro:/opt/cerebro/conf 
    networks:
      elastic-network:
        ipv4_address: 172.25.0.105
    ports:
      - "9000:9000"
    links:
      - es-nginx
      - elasticsearch-node1
      - elasticsearch-node2
      - elasticsearch-node3

  es-kibana:
    image: kibana:latest
    networks:
      elastic-network:
        ipv4_address: 172.25.0.106
    links:
      - elasticsearch-node1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-node1:9200
